### ISSUE TITLE
add an info button to the scarab

### ISSUE THREAD

**Issue by burritojustice** [mapzen/scarab#1]
add a pop-up info button to the scarab. this would help explain standalone tangram-view maps, including those that get retweeted and separated from their posts.

![image](https://cloud.githubusercontent.com/assets/3979711/26367938/0adca492-3fa5-11e7-8781-cec6073a51f7.png)

![image](https://cloud.githubusercontent.com/assets/3979711/26367899/f5221e2a-3fa4-11e7-9d35-55b3842b17f1.png)

This would pop up and go away on a click.

Maybe something like

```L.Mapzen.bug({
  name: 'Web Map',
  link: 'https://erasermap.com/maps',
  tweet: '@mapzen',
  repo: 'https://github.com/mapzen/web-map'
  info: 'a few dozen words of explanatory text (and html for links)'
});```

see also https://github.com/tangrams/tangram-play/issues/734

originally posted in mapzen.js: https://github.com/mapzen/mapzen.js/issues/383

**Comment by louh** [comment]
Note: We will not be permitting raw HTML in descriptions. This poses a [security risk](https://www.owasp.org/index.php/Testing_for_HTML_Injection_(OTG-CLIENT-003)), for instance, it would be possible for me to write a scene, save it to Mapzen, and send it to someone with injected code that could hijack that person's credentials and take over their Mapzen account.

For the current implementation we are allowing a text-only field. In the future, we may expand this to permit Markdown syntax.

**Comment by louh** [comment]
Closed via https://github.com/mapzen/scarab/pull/5.

Mapzen.js integration pending here: https://github.com/mapzen/mapzen.js/pull/400
